   [build]
   command = "npm cache clean --force && npm install --force && npm run build"
   publish = ".next"

   [build.environment]
   NODE_VERSION = "22.12.0"
   NPM_FLAGS = "--legacy-peer-deps --force"
